### ISSUE TITLE
Creating asset map with new version of GeoJson

### ISSUE THREAD

**Issue by nmalan** [ocefpaf/secoora_assets_map#3]
In trying to use this method to create an asset map (in my case for the Integrated marine observing system in Australia, I run into an issue with the new geojson methods in folium (geo_json has been replaced by folium.GeoJson, I think), giving the following error message in assets_map.ipynb

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-cebe82411115> in <module>
     12 for json in jsons:
     13     kw = dict(fill_color='#DEFFDE', line_color='#AECCAE')
---> 14     mapa.geo_json(geo_path=json, **kw)
     15 
     16 

AttributeError: 'Map' object has no attribute 'geo_json'
```
As a folium newbie, I'm struggling to update the functions with the new method, would appreciate any advice!

**Comment by ocefpaf** [comment]
Please open an issue on the folium repository. This repo here was an exercise and it is quite outdated!
